# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get install openssl
      - run: sudo apt-get install python3 python-pip python-dev build-essential
      - run: pip install awscli --upgrade --user
      - run: echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run: source ~/.bashrc
      - run: aws --version
      - run: sudo npm install -g @angular/cli semver
      - run: printf '%s\n' "ACCESS_KEY_ID=$ACCESS_KEY_ID" "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" "GITHUB_TOKEN"=$GITHUB_TOKEN" >> .env

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Setup Pug Compiler
          command: node ./ng-add-pug-loader.js

      - run:
          name: Build
          command: npm run build

      - run:
          name: Deploy
          command: sh bin/deploy.sh
